# On PR to main, install dependencies, test, and build React app and push /dist to s3://mqtt.anmiller.com.

name: Upload site to S3

env:
  S3_BUCKET_NAME: mqtt.anmiller.com
  WORKING_DIRECTORY: ./
  DIST_DIRECTORY: ./packages/web/dist/

on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests (unit)
        run: yarn test

      # - name: Run tests (integration)
      #   run: yarn test

      - name: Build site
        run: yarn build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ${{ env.WORKING_DIRECTORY }}${{ env.DIST_DIRECTORY }} s3://${{ env.S3_BUCKET_NAME }} --delete

        env:
          CI: true